
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hassan Akhlaq
 */
public class ResultForm extends javax.swing.JFrame {

    /**
     * Creates new form ResultForm
     */
    public ResultForm() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        usernameL.setText(Helper.username);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        saveResultToDbB = new javax.swing.JButton();
        saveResultB = new javax.swing.JButton();
        discardResultsB = new javax.swing.JButton();
        previewResultImageB = new javax.swing.JButton();
        backToUploadB = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        searchDate = new com.toedter.calendar.JDateChooser();
        searchB = new javax.swing.JLabel();
        usernameL = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        closeB1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 48)); // NOI18N
        jLabel2.setText("Torn Image Reconstruction");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel3.setText("Feel free to repair your torn images..!!");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jPanel2.setBackground(new java.awt.Color(32, 47, 90));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(106, 116, 145));

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Congratulations..!!");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addComponent(jLabel11)
                .addContainerGap(246, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 690, 40));

        saveResultToDbB.setBackground(new java.awt.Color(0, 18, 50));
        saveResultToDbB.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        saveResultToDbB.setForeground(new java.awt.Color(255, 255, 255));
        saveResultToDbB.setText("Save to Database");
        saveResultToDbB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        saveResultToDbB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveResultToDbBMouseClicked(evt);
            }
        });
        jPanel2.add(saveResultToDbB, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 280, 50));

        saveResultB.setBackground(new java.awt.Color(0, 18, 50));
        saveResultB.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        saveResultB.setForeground(new java.awt.Color(255, 255, 255));
        saveResultB.setText("Save to Computer");
        saveResultB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        saveResultB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveResultBMouseClicked(evt);
            }
        });
        jPanel2.add(saveResultB, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 280, 50));

        discardResultsB.setBackground(new java.awt.Color(0, 18, 50));
        discardResultsB.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        discardResultsB.setForeground(new java.awt.Color(255, 255, 255));
        discardResultsB.setText("Discard Result");
        discardResultsB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(discardResultsB, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 560, 50));

        previewResultImageB.setBackground(new java.awt.Color(0, 18, 50));
        previewResultImageB.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        previewResultImageB.setForeground(new java.awt.Color(255, 255, 255));
        previewResultImageB.setText("Preview Result");
        previewResultImageB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        previewResultImageB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                previewResultImageBMouseClicked(evt);
            }
        });
        jPanel2.add(previewResultImageB, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 560, 50));

        backToUploadB.setBackground(new java.awt.Color(106, 116, 145));
        backToUploadB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backToUploadBMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Back to Main Page");

        javax.swing.GroupLayout backToUploadBLayout = new javax.swing.GroupLayout(backToUploadB);
        backToUploadB.setLayout(backToUploadBLayout);
        backToUploadBLayout.setHorizontalGroup(
            backToUploadBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backToUploadBLayout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addComponent(jLabel12)
                .addContainerGap(254, Short.MAX_VALUE))
        );
        backToUploadBLayout.setVerticalGroup(
            backToUploadBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(backToUploadB, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 690, -1));

        jPanel1.setBackground(new java.awt.Color(0, 18, 50));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Back_20px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel19)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel19)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        searchB.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        searchB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Search_25px.png"))); // NOI18N
        searchB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchBMouseClicked(evt);
            }
        });

        usernameL.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        usernameL.setText("User");

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_User_25px.png"))); // NOI18N

        closeB1.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        closeB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Cancel_20px.png"))); // NOI18N
        closeB1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeB1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchB)
                .addGap(13, 13, 13)
                .addComponent(searchDate, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183)
                .addComponent(jLabel4)
                .addGap(15, 15, 15)
                .addComponent(usernameL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeB1)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(closeB1)
                    .addComponent(jLabel4)
                    .addComponent(usernameL)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(searchB))
                    .addComponent(searchDate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 875, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 835, Short.MAX_VALUE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(50, 50, 50)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        cleanMatlabFolder();
        FileManipulationForm manform = new FileManipulationForm();
        this.setVisible(false);
        manform.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel1MouseClicked

    private void previewResultImageBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previewResultImageBMouseClicked
        try {
            File f = new File(Helper.docsPath + "MatlabCode\\result.jpg");
            Desktop dt = Desktop.getDesktop();
            dt.open(f);
        } catch (IOException ex) {
            Logger.getLogger(ResultForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_previewResultImageBMouseClicked

    private void backToUploadBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backToUploadBMouseClicked
        cleanMatlabFolder();
        UploadFileForm form = new UploadFileForm();
        this.setVisible(false);
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backToUploadBMouseClicked

    private void saveResultBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveResultBMouseClicked
        try {
            File resultFile = new File(Helper.docsPath + "MatlabCode\\result.jpg");
            File destFile = new File(Helper.imgFolderPath+"\\result.jpg");
            Files.copy(resultFile.toPath(), destFile.toPath(), StandardCopyOption.REPLACE_EXISTING);
            JOptionPane.showMessageDialog(rootPane, "Result Saved Successfully");
        } catch (IOException ex) {
            Logger.getLogger(ResultForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveResultBMouseClicked

    private void saveResultToDbBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveResultToDbBMouseClicked
        saveResultBMouseClicked(evt);
        
        SimpleDateFormat fmt = new SimpleDateFormat("MMM d,yyyy hh:mm:ss");
        String actionTime = fmt.format(Helper.actionDate);
        
        ArrayList<String> param=new ArrayList<String>();
        String insertRecordQuery = "Insert into TESTS(CNIC, IMAGES_PATH,PIECES,TEST_DATE) "
                                    + "values(?,?,?,Parse (? as DateTime2))";
        param.add(Helper.cnic);
        param.add(Helper.imgFolderPath);
        param.add(Integer.toString(Helper.pieces) );
        param.add(actionTime);
        
        if(DBHandler.runUpdate(insertRecordQuery,param))
            JOptionPane.showMessageDialog(null, "Reconstruction Recorded Succesfully","Message",JOptionPane.INFORMATION_MESSAGE);
        else
            JOptionPane.showMessageDialog(rootPane, "Reconstruction could not Recorded","Error",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_saveResultToDbBMouseClicked

    private void searchBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBMouseClicked
        if(this.searchDate.getDate()!=null)
        {
            Helper.searchDate=this.searchDate.getDate();
            Helper.searchFlag = true;
            RecordsForm form;
            try {
                form = new RecordsForm();
                this.setVisible(false);
                form.setVisible(true);
                this.dispose();
            } catch (SQLException | ParseException ex) {
                Logger.getLogger(UserPanelForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_searchBMouseClicked

    private void closeB1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeB1MouseClicked
        int option = JOptionPane.showConfirmDialog(rootPane, "Are you sure to quit the Program");
        if(option==JOptionPane.OK_OPTION)
        {
            DBHandler.closeConnection();
            System.exit(0);
        }
    }//GEN-LAST:event_closeB1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResultForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResultForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResultForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResultForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResultForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backToUploadB;
    private javax.swing.JLabel closeB1;
    private javax.swing.JButton discardResultsB;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JButton previewResultImageB;
    private javax.swing.JButton saveResultB;
    private javax.swing.JButton saveResultToDbB;
    private javax.swing.JLabel searchB;
    private com.toedter.calendar.JDateChooser searchDate;
    private javax.swing.JLabel usernameL;
    // End of variables declaration//GEN-END:variables

    private void cleanMatlabFolder() {
        try {
            File filesToDelete = new File(Helper.docsPath+"MatlabCode\\");
            File [] files = filesToDelete.listFiles();
            
            for (File file : files) {
                if(file.getName().endsWith(".jpg"))
                    Files.delete(file.toPath());
            }
            File sampleFile = new File(Helper.docsPath+"sample.jpg");
            Files.delete(sampleFile.toPath());
        } catch (IOException ex) {
            Logger.getLogger(ResultForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
