
import com.sun.glass.events.KeyEvent;
import com.toedter.calendar.JDateChooser;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hassan Akhlaq
 */
public class SignUpForm extends javax.swing.JFrame {

    /**
     * Creates new form SignUpForm
     */
    public SignUpForm() {
        initComponents();
        ButtonGroup bg = new ButtonGroup();
        bg.add(maleRB);
        bg.add(femaleRB);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        
        Calendar cal = Calendar.getInstance();
        cal.add(Calendar.YEAR, -18);//15 year before
        Date max = cal.getTime();

        Date min = new Date(0);//actual date
        //set your dates in your JDateChooser
        this.dateOfBirth.setSelectableDateRange(min, max);
        this.dateOfBirth.setDate(max);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        usernameTF = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        cnicTF = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        femaleRB = new javax.swing.JRadioButton();
        maleRB = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        passwordTF = new javax.swing.JPasswordField();
        signUpProceedB = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        dateOfBirth = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        closeB1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 18, 50));
        jPanel1.setPreferredSize(new java.awt.Dimension(40, 286));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Back_20px.png"))); // NOI18N
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 252, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 540));

        jPanel2.setBackground(new java.awt.Color(32, 47, 90));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(106, 116, 145));

        jLabel12.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Sign-up Details:");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(505, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 690, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 2, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Username");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, 30));

        usernameTF.setBackground(new java.awt.Color(32, 47, 90));
        usernameTF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        usernameTF.setForeground(new java.awt.Color(255, 255, 255));
        usernameTF.setBorder(null);
        usernameTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                usernameTFKeyTyped(evt);
            }
        });
        jPanel2.add(usernameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 210, 30));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 210, 10));

        cnicTF.setBackground(new java.awt.Color(32, 47, 90));
        cnicTF.setColumns(13);
        cnicTF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cnicTF.setForeground(new java.awt.Color(255, 255, 255));
        cnicTF.setBorder(null);
        cnicTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cnicTFKeyTyped(evt);
            }
        });
        jPanel2.add(cnicTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 210, 30));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 210, 20));

        jLabel14.setFont(new java.awt.Font("Segoe UI Semibold", 2, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("CNIC");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 120, 30));

        femaleRB.setBackground(new java.awt.Color(32, 47, 90));
        femaleRB.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        femaleRB.setForeground(new java.awt.Color(255, 255, 255));
        femaleRB.setText("Female");
        jPanel2.add(femaleRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, -1, 30));

        maleRB.setBackground(new java.awt.Color(32, 47, 90));
        maleRB.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        maleRB.setForeground(new java.awt.Color(255, 255, 255));
        maleRB.setText("Male");
        jPanel2.add(maleRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI Semibold", 2, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Gender ");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, 30));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 210, 10));

        jLabel16.setFont(new java.awt.Font("Segoe UI Semibold", 2, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Password ");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 100, 30));

        passwordTF.setBackground(new java.awt.Color(32, 47, 90));
        passwordTF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        passwordTF.setForeground(new java.awt.Color(255, 255, 255));
        passwordTF.setBorder(null);
        passwordTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passwordTFKeyTyped(evt);
            }
        });
        jPanel2.add(passwordTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 210, 30));

        signUpProceedB.setBackground(new java.awt.Color(0, 18, 50));
        signUpProceedB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        signUpProceedB.setForeground(new java.awt.Color(255, 255, 255));
        signUpProceedB.setText("Proceed");
        signUpProceedB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        signUpProceedB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signUpProceedBMouseClicked(evt);
            }
        });
        jPanel2.add(signUpProceedB, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 300, 40));

        jLabel13.setFont(new java.awt.Font("Segoe UI Semibold", 2, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Date Of Birth");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, 30));

        dateOfBirth.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(dateOfBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 210, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 835, 270));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 48)); // NOI18N
        jLabel2.setText("Torn Image Reconstruction");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel3.setText("Feel free to repair your torn images..!!");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 830, 200));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeB1.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        closeB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Cancel_20px.png"))); // NOI18N
        closeB1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeB1MouseClicked(evt);
            }
        });
        jPanel4.add(closeB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 8, 30, 30));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 835, 52));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        Home home = new Home();
        home.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jPanel1MouseClicked

    private void cnicTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cnicTFKeyTyped
        if(this.cnicTF.getText().length()>12)
        {
            evt.consume();
            getToolkit().beep();
        }
        else
            allowOnlyDigits(evt);
    }//GEN-LAST:event_cnicTFKeyTyped

    private void usernameTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameTFKeyTyped
        if(this.usernameTF.getText().length()>49)
        {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_usernameTFKeyTyped

    private void passwordTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordTFKeyTyped
        if(this.passwordTF.getText().length()>29)
        {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_passwordTFKeyTyped

    private void signUpProceedBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpProceedBMouseClicked
        // TODO add your handling code here:
        
        String username = usernameTF.getText();
        if(username==null || username.length()==0)
        {
            JOptionPane.showMessageDialog(rootPane, "Please enter Username");
            return;
        }
        String cnic = cnicTF.getText();
        if(cnic==null || cnic.length()==0)
        {
            JOptionPane.showMessageDialog(rootPane, "Please enter CNIC");
            return;
        }
        if(cnic.length()!=13)
        {
            JOptionPane.showMessageDialog(rootPane, "CNIC must be 13 letters","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String cnicCheckQuery = "Select * from USERS where CNIC="+cnic;
        ResultSet rs = DBHandler.runQuery(cnicCheckQuery);
       
        try {
            if(rs.next())
            {
                JOptionPane.showMessageDialog(rootPane, "CNIC Already Exists in Database","Error",JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (SQLException ex) {
            Logger.getLogger(SignUpForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        String gender="";
        if(maleRB.isSelected())
            gender="Male";
        else if(femaleRB.isSelected())
            gender="Female";
        
        if(gender=="")
        {
            JOptionPane.showMessageDialog(rootPane, "Please enter Gender");
            return;
        }
        
        String password = passwordTF.getText();
        if(password==null || password.length()==0)
        {
            JOptionPane.showMessageDialog(rootPane, "Please enter Password");
            return;
        }
        Date dob = dateOfBirth.getDate(); 
        if(dob==null)
        {
            JOptionPane.showMessageDialog(rootPane, "Please enter Date Of Birth");
            return;
        }
        SimpleDateFormat fmt = new SimpleDateFormat("MMM d,yyyy");
        String dateOfBirth = fmt.format(dob);
        
        
        ArrayList<String> param=new ArrayList<String>();
        String signUpQuery = "Insert into USERS(CNIC, USERNAME, PASSWORD, DOB, GENDER) "
                                    + "values(?,?,?,Parse (? as DateTime2),?)";
        
        param.add(cnic);
        param.add(username);
        param.add(password);
        param.add(dateOfBirth);
        param.add(gender);
        
        if(DBHandler.runUpdate(signUpQuery,param))
        {
            JOptionPane.showMessageDialog(null, "Sign Up Succesful","Message",JOptionPane.INFORMATION_MESSAGE);
            Helper.username=username;
            Helper.cnic = cnic;
            UserPanelForm userpanelform = new UserPanelForm();
            userpanelform.setVisible(true);
            this.setVisible(false);   
            this.dispose();
        }
        else
            JOptionPane.showMessageDialog(rootPane, "Could not register user","Error",JOptionPane.ERROR_MESSAGE);

    }//GEN-LAST:event_signUpProceedBMouseClicked

    private void closeB1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeB1MouseClicked
        int option = JOptionPane.showConfirmDialog(rootPane, "Are you sure to quit the Program");
        if(option==JOptionPane.OK_OPTION)
        {
            DBHandler.closeConnection();
            System.exit(0);
        }
    }//GEN-LAST:event_closeB1MouseClicked

    public void allowOnlyDigits(java.awt.event.KeyEvent evt){
        char c=evt.getKeyChar();
        
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACKSPACE || c==KeyEvent.VK_DELETE)){
            evt.consume();
            getToolkit().beep();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel closeB1;
    private javax.swing.JTextField cnicTF;
    private com.toedter.calendar.JDateChooser dateOfBirth;
    private javax.swing.JRadioButton femaleRB;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JRadioButton maleRB;
    private javax.swing.JPasswordField passwordTF;
    private javax.swing.JButton signUpProceedB;
    private javax.swing.JTextField usernameTF;
    // End of variables declaration//GEN-END:variables
}
