
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hassan Akhlaq
 */
public class UserPanelForm extends javax.swing.JFrame {

    /**
     * Creates new form UserPanelForm
     */
    public UserPanelForm() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        usernameL.setText(Helper.username);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        uploadFileB = new javax.swing.JButton();
        manageRecordsB = new javax.swing.JButton();
        viewRecordsB = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        searchB = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        usernameL = new javax.swing.JLabel();
        searchDate = new com.toedter.calendar.JDateChooser();
        closeB1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 18, 50));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Back_20px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 10, Short.MAX_VALUE)
                    .addComponent(jLabel19)
                    .addGap(0, 10, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel18)
                .addContainerGap(523, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 265, Short.MAX_VALUE)
                    .addComponent(jLabel19)
                    .addGap(0, 265, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 550));

        jPanel2.setBackground(new java.awt.Color(32, 47, 90));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(106, 116, 145));

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("User Panel");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addComponent(jLabel11)
                .addContainerGap(290, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 690, 40));

        uploadFileB.setBackground(new java.awt.Color(0, 18, 50));
        uploadFileB.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        uploadFileB.setForeground(new java.awt.Color(255, 255, 255));
        uploadFileB.setText("Upload File");
        uploadFileB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        uploadFileB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadFileBActionPerformed(evt);
            }
        });
        jPanel2.add(uploadFileB, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, 190, 80));

        manageRecordsB.setBackground(new java.awt.Color(0, 18, 50));
        manageRecordsB.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        manageRecordsB.setForeground(new java.awt.Color(255, 255, 255));
        manageRecordsB.setText("Manage Records");
        manageRecordsB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        manageRecordsB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageRecordsBActionPerformed(evt);
            }
        });
        jPanel2.add(manageRecordsB, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 190, 80));

        viewRecordsB.setBackground(new java.awt.Color(0, 18, 50));
        viewRecordsB.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        viewRecordsB.setForeground(new java.awt.Color(255, 255, 255));
        viewRecordsB.setText("View Records");
        viewRecordsB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewRecordsB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewRecordsBMouseClicked(evt);
            }
        });
        jPanel2.add(viewRecordsB, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 190, 80));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 830, 300));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 48)); // NOI18N
        jLabel2.setText("Torn Image Reconstruction");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel3.setText("Feel free to repair your torn images..!!");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 830, 200));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchB.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        searchB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Search_25px.png"))); // NOI18N
        searchB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchBMouseClicked(evt);
            }
        });
        jPanel4.add(searchB, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_User_25px.png"))); // NOI18N
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, -1, -1));

        usernameL.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        usernameL.setText("User");
        jPanel4.add(usernameL, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, -1));
        jPanel4.add(searchDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 240, 30));

        closeB1.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        closeB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Cancel_20px.png"))); // NOI18N
        closeB1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeB1MouseClicked(evt);
            }
        });
        jPanel4.add(closeB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 8, 30, 30));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 830, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uploadFileBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadFileBActionPerformed
        // TODO add your handling code here:
        UploadFileForm uploadfileform = new UploadFileForm();
        uploadfileform.setVisible(true);
        this.setVisible(false);   
        this.dispose();
    }//GEN-LAST:event_uploadFileBActionPerformed

    private void manageRecordsBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageRecordsBActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Manage Records not avaiable");
    }//GEN-LAST:event_manageRecordsBActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        int option = JOptionPane.showConfirmDialog(rootPane, "Please Confirm to Log Out");
        if(option==JOptionPane.OK_OPTION)
        {
            Helper.cnic="";
            Helper.username="";
            
            Home form = new Home();
            form.setVisible(true);
            this.dispose();
            this.setVisible(false);
        }
    }//GEN-LAST:event_jPanel1MouseClicked

    private void viewRecordsBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewRecordsBMouseClicked
        RecordsForm form;
        try {
            form = new RecordsForm();
            this.setVisible(false);
            form.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(UserPanelForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(UserPanelForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_viewRecordsBMouseClicked

    private void searchBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBMouseClicked
        if(this.searchDate.getDate()!=null)
        {
            Helper.searchDate=this.searchDate.getDate();
            Helper.searchFlag = true;
            RecordsForm form;
            try {
                form = new RecordsForm();
                this.setVisible(false);
                form.setVisible(true);
                this.dispose();
            } catch (SQLException | ParseException ex) {
                Logger.getLogger(UserPanelForm.class.getName()).log(Level.SEVERE, null, ex);
            }   
        }
    }//GEN-LAST:event_searchBMouseClicked

    private void closeB1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeB1MouseClicked
        int option = JOptionPane.showConfirmDialog(rootPane, "Are you sure to quit the Program");
        if(option==JOptionPane.OK_OPTION)
        {
            DBHandler.closeConnection();
            System.exit(0);
        }
    }//GEN-LAST:event_closeB1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserPanelForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserPanelForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserPanelForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserPanelForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserPanelForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel closeB1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JButton manageRecordsB;
    private javax.swing.JLabel searchB;
    private com.toedter.calendar.JDateChooser searchDate;
    private javax.swing.JButton uploadFileB;
    private javax.swing.JLabel usernameL;
    private javax.swing.JButton viewRecordsB;
    // End of variables declaration//GEN-END:variables
}
